# Generated by Django 4.0.1 on 2022-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(default='', help_text='Username', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre', max_length=15)),
                ('surname', models.CharField(help_text='Nombre', max_length=30)),
                ('mail', models.EmailField(help_text='Email address', max_length=30)),
                ('password', models.CharField(help_text='pass', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
