# Generated by Django 4.0.1 on 2022-01-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_user_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
