# Generated by Django 4.0.1 on 2022-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
