# Generated by Django 4.0.1 on 2022-01-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dateEnd',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='dateStart',
            new_name='startDate',
        ),
    ]
