# Generated by Django 4.0.1 on 2022-01-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_workers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
