# Generated by Django 4.0.1 on 2022-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_worker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='title',
        ),
        migrations.AddField(
            model_name='worker',
            name='titles',
            field=models.CharField(default='ñlaksj', help_text='Titles (comma separated)', max_length=500),
        ),
        migrations.AlterField(
            model_name='worker',
            name='collaborations',
            field=models.CharField(help_text='Collaborations(comma separated)', max_length=500),
        ),
    ]
