# Generated by Django 4.0.1 on 2022-01-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_worker_title_worker_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='titles',
            field=models.CharField(help_text='Titles (comma separated)', max_length=500),
        ),
    ]
