# Generated by Django 4.0.1 on 2022-01-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_worker_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
