# Generated by Django 4.0.1 on 2022-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_worker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtags', models.CharField(help_text='Hashtags', max_length=50)),
                ('title', models.CharField(help_text='Nombre', max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(help_text='Description', max_length=500)),
                ('content', models.CharField(help_text='content', max_length=2000)),
                ('references', models.CharField(help_text='References', max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
