# Generated by Django 4.0.1 on 2022-01-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(help_text='Username', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Password', max_length=20)),
                ('mail', models.EmailField(help_text='Email address', max_length=30)),
                ('userType', models.CharField(max_length=1)),
            ],
        ),
    ]
